dl_toolbox: "torch"  # The deep learning toolbox. Choices: "torch", "mindspore", "tensorlayer"
project_name: "netenv_ppo_1"
logger: "tensorboard"  # Choices: tensorboard, wandb.
wandb_user_name: "wmqbit"
render: False
render_mode: 'rgb_array' # Choices: 'human', 'rgb_array'.
fps: 50
test_mode: False
device: "cuda:0"  # Choose an calculating device. PyTorch: "cpu", "cuda:0"; TensorFlow: "cpu"/"CPU", "gpu"/"GPU"; MindSpore: "CPU", "GPU", "Ascend", "Davinci".
distributed_training: False  # Whether to use multi-GPU for distributed training.
master_port: '12355'  # The master port for current experiment when use distributed training.

agent: "PPO_Clip"  # choice: PPO_Clip, PPO_KL
env_name: "NetEnv"
env_id: "NetEnv-Net30-v0"
env_seed: 1
RGBImgPartialObsWrapper: False
ImgObsWrapper: False
vectorize: "DummyVecEnv"
learner: "MYPPOCLIP_Learner"
policy: "Categorical_AC"  # choice: Gaussian_AC for continuous actions, Categorical_AC for discrete actions.
representation: "Basic_MLP"

representation_hidden_size: [64, 32]
actor_hidden_size: [32, 16]
critic_hidden_size: [32, 16]
# representation_hidden_size: [256,]
# actor_hidden_size: [256,]
# critic_hidden_size: [256,]
activation: "leaky_relu"

seed: 79811
parallels: 50
running_steps: 10000000
horizon_size: 128  # the horizon size for an environment, buffer_size = horizon_size * parallels.
n_epochs: 16
n_minibatch: 8
learning_rate: 0.0001

vf_coef: 0.25
ent_coef: 0.0
target_kl: 0.25  # for PPO_KL agent
kl_coef: 1.0  # for PPO_KL agent
clip_range: 0.2  # for PPO_Clip agent
gamma: 0.99
use_gae: True
gae_lambda: 0.95
use_advnorm: True

use_grad_clip: True  # gradient normalization
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
grad_clip_norm: 0.5
use_actions_mask: False
use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 1000
test_episode: 10
log_dir: "../logs/ppo/"
model_dir: "../models/ppo/"
